db_conn_info: "postgres://filesync:secret@192.168.1.157:6010/filesync?sslmode=disable"

oauth:
  ClientId: "FILESYNC_DEV"
  TokenUrl: "https://id.swish-cloud.com/op/oauth2/token"
  AuthUrl: "https://id.swish-cloud.com/op/oauth2/auth"
  Secret: "lTCNCgnfTTy8RlTPW0nJ"
  LogoutUrl: "https://id.swish-cloud.com/op/oauth2/sessions/logout"
  LogoutRedirectUrl: "http://localhost:8080"
  JWKJsonUrl: "https://id.swish-cloud.com/op/.well-known/jwks.json"