db_conn_info: "postgres://filesync:secret@localhost:6010/filesync?sslmode=disable"

oauth:
  ClientId: "FILESYNC_WEB"
  TokenUrl: "https://localhost:8010/oauth2/token"
  AuthUrl: "https://localhost:8010/oauth2/auth"
  Secret: "FILESYNC_WEB_SECRET"
  RedirectURL: "https://localhost:2002/login-callback"
  NativeAppRedirectURL: "https://localhost:11109/.approvalnativeapp"
  UserInfoURL: "https://localhost:11109/user_info"
  IntrospectTokenURL: "https://localhost:11109/api/introspect-token"
  LogoutUrl: "https://localhost:8010/oauth2/sessions/logout"
  LogoutRedirectUrl: "https://localhost:2002"
  JWKJsonUrl: "https://localhost:8010/.well-known/jwks.json"
file_location: .cache/files/